using Content.Client.UserInterface.Controls;
// _CS start: toy control consent integration
using Robust.Client.ToyControl;
using Content.Shared._CS.CCVar;
// _CS end: toy control consent integration
using Content.Shared.Floofstation.FSCVars; // Flooftier
using Content.Shared.Consent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;
// _CS start: async intiface connection test
using System.Threading.Tasks;
// _CS end: async intiface connection test

namespace Content.Client.Consent.UI.Windows;

[GenerateTypedNameReferences]
public sealed partial class ConsentWindow : FancyWindow
{
    [Dependency] private readonly IClientConsentManager _consentManager = default!;
    [Dependency] private readonly IConfigurationManager _configManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    private readonly List<EntryState> _entries = new();
    // _CS start: toy control consent state
    private string _pendingIntifaceAddress = string.Empty;
    private LineEdit? _intifaceAddressEdit;
    private Label? _intifaceStatusLabel;
    private Button? _intifaceTestButton;
    private int _intifaceTestVersion;
    // _CS end: toy control consent state

    public ConsentWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Set up tab titles
        ConsentTabContainer.SetTabTitle(0, Loc.GetString("consent-window-tab-character"));
        ConsentTabContainer.SetTabTitle(1, Loc.GetString("consent-window-tab-account"));
        ConsentTabContainer.SetTabTitle(2, Loc.GetString("consent-window-tab-preview"));

        // _CS start: save consent and intiface address together
        SaveConsentSettings.OnPressed += OnSaveConsentSettingsPressed;
        // _CS end: save consent and intiface address together

        _consentManager.OnServerDataLoaded += UpdateUi;
        if (_consentManager.HasLoaded)
            UpdateUi();

        CharacterConsentFreetext.Placeholder = new Rope.Leaf(Loc.GetString("consent-window-character-freetext-placeholder"));
        CharacterConsentFreetext.OnTextChanged += _ => { UnsavedChanges(); UpdatePreview(); };

        ConsentFreetext.Placeholder = new Rope.Leaf(Loc.GetString("consent-window-freetext-placeholder"));
        ConsentFreetext.OnTextChanged += _ => { UnsavedChanges(); UpdatePreview(); };

        // Update preview when switching to preview tab
        ConsentTabContainer.OnTabChanged += _ => UpdatePreview();
    }

    private PlayerConsentSettings GetSettings()
    {
        var characterText = Rope.Collapse(CharacterConsentFreetext.TextRope);
        var accountText = Rope.Collapse(ConsentFreetext.TextRope);
        var toggles = new Dictionary<ProtoId<ConsentTogglePrototype>, string>();

        foreach (var entry in _entries)
        {
            if (entry.Button != null && entry.Button.Pressed)
                toggles[entry.Consent.ID] = "on";
        }

        return new(accountText, characterText, toggles);
    }

    // _CS start: persist archived intiface address from consent window
    private void OnSaveConsentSettingsPressed(BaseButton.ButtonEventArgs args)
    {
        SaveConsentSettings.Disabled = true;
        _configManager.SetCVar(CSCVars.IntifaceAddress, _pendingIntifaceAddress);
        SetIntifaceStatus(Loc.GetString("toy-control-intiface-status-unknown"));
        _consentManager.UpdateConsent(GetSettings());
        SaveLabel.Text = string.Empty;
    }
    // _CS end: persist archived intiface address from consent window

    private void UnsavedChanges()
    {
        // Validate freetext length
        var maxLength = _configManager.GetCVar(FSCVars.ConsentFreetextMaxLength); // Flooftier
        var characterLength = Rope.Collapse(CharacterConsentFreetext.TextRope).Length;
        var accountLength = Rope.Collapse(ConsentFreetext.TextRope).Length;

        if (characterLength > maxLength)
        {
            SaveLabel.Text = Loc.GetString("consent-window-char-limit-warning", ("length", characterLength), ("maxLength", maxLength));
            SaveConsentSettings.Disabled = true;
            return;
        }

        if (accountLength > maxLength)
        {
            SaveLabel.Text = Loc.GetString("consent-window-char-limit-warning", ("length", accountLength), ("maxLength", maxLength));
            SaveConsentSettings.Disabled = true;
            return;
        }

        // If everything is valid, enable save button and inform user they need to save.
        SaveLabel.Text = Loc.GetString("consent-window-unsaved-changes");
        SaveConsentSettings.Disabled = false;
    }

    private void UpdatePreview()
    {
        if (ConsentTabContainer.CurrentTab != 2)
            return;

        var characterText = Rope.Collapse(CharacterConsentFreetext.TextRope);
        var accountText = Rope.Collapse(ConsentFreetext.TextRope);

        var previewMessage = new FormattedMessage();

        // Show character-specific text first if it exists
        if (!string.IsNullOrWhiteSpace(characterText))
        {
            // Parse markup in character text
            var characterMessage = FormattedMessage.FromMarkupPermissive(characterText);
            previewMessage.AddMessage(characterMessage);
        }

        // Show account text after if it exists
        if (!string.IsNullOrWhiteSpace(accountText))
        {
            if (!string.IsNullOrWhiteSpace(characterText))
            {
                previewMessage.AddText("\n\n");
            }
            // Parse markup in account text
            var accountMessage = FormattedMessage.FromMarkupPermissive(accountText);
            previewMessage.AddMessage(accountMessage);
        }

        // If neither exists, show default message
        if (string.IsNullOrWhiteSpace(characterText) && string.IsNullOrWhiteSpace(accountText))
        {
            previewMessage.AddText(Loc.GetString("consent-examine-not-set"));
        }

        PreviewText.SetMessage(previewMessage);
    }

    private void AddConsentEntry(ConsentTogglePrototype prototype, PlayerConsentSettings consent)
    {
        var state = new EntryState { Consent = prototype };

        var container = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(5f, 5f)
        };

        var name = new Label
        {
            Text = Loc.GetString($"consent-{prototype.ID}-name"),
            HorizontalExpand = true
        };

        var buttonOff = new Button { Text = "Off" };
        buttonOff.StyleClasses.Add("OpenRight");
        buttonOff.Pressed = true;

        var buttonOn = new Button { Text = "On" };
        buttonOn.StyleClasses.Add("OpenLeft");
        state.Button = buttonOn;

        buttonOff.OnPressed += _ => { ButtonOnPress(buttonOff, buttonOn); UpdatePreview(); };
        buttonOn.OnPressed += _ => { ButtonOnPress(buttonOn, buttonOff); UpdatePreview(); };

        foreach (var toggle in consent.Toggles)
        {
            if (toggle.Key == prototype.ID && toggle.Value == "on")
            {
                buttonOn.Pressed = true;
                buttonOff.Pressed = false;
                continue;
            }
        }

        header.AddChild(name);
        header.AddChild(buttonOff);
        header.AddChild(buttonOn);

        // _CS start: RemoteToyControl inline Intiface settings
        // For RemoteToyControl, append a cog button that reveals an Intiface address field
        if (prototype.ID == "RemoteToyControl")
        {
            var settingsPanel = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(5f, 2f),
                Visible = false
            };

            var settingsRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            var addressLabel = new Label { Text = Loc.GetString("toy-control-intiface-address-label") };
            var addressEdit = new LineEdit
            {
                Text = _pendingIntifaceAddress,
                HorizontalExpand = true,
                PlaceHolder = "ws://127.0.0.1:12345"
            };
            addressEdit.OnTextChanged += args =>
            {
                _pendingIntifaceAddress = args.Text;
                SetIntifaceStatus(Loc.GetString("toy-control-intiface-status-pending-save"));
                UnsavedChanges();
            };

            var testButton = new Button
            {
                Text = Loc.GetString("toy-control-intiface-test-button")
            };
            testButton.OnPressed += OnTestIntifaceButtonPressed;

            var statusLabel = new Label
            {
                Text = Loc.GetString("toy-control-intiface-status-unknown")
            };

            settingsRow.AddChild(addressLabel);
            settingsRow.AddChild(addressEdit);
            settingsRow.AddChild(testButton);

            settingsPanel.AddChild(settingsRow);
            settingsPanel.AddChild(statusLabel);

            _intifaceAddressEdit = addressEdit;
            _intifaceStatusLabel = statusLabel;
            _intifaceTestButton = testButton;

            var cogButton = new Button { Text = "⚙" };
            cogButton.OnPressed += _ => { settingsPanel.Visible = !settingsPanel.Visible; };
            header.AddChild(cogButton);

            container.AddChild(header);
            container.AddChild(settingsPanel);
        }
        else
        {
            container.AddChild(header);
        }
        // _CS end: RemoteToyControl inline Intiface settings

        var desc = new Label
        {
            Text = Loc.GetString($"consent-{prototype.ID}-desc"),
        };

        container.AddChild(desc);

        var wrapper = new PanelContainer();
        wrapper.StyleClasses.Add("PdaBorderRect");

        wrapper.AddChild(container);
        if (ConsentList.Disposed)
            return;
        ConsentList.AddChild(wrapper);

        _entries.Add(state);
    }

    private void ButtonOnPress(Button currentButton, Button otherbutton)
    {
        currentButton.Pressed = true;
        otherbutton.Pressed = false;
        UnsavedChanges();
    }

    public void UpdateUi()
    {
        var consent = _consentManager.GetConsent();
        // _CS start: keep pending address in sync with archived cvar
        _pendingIntifaceAddress = _configManager.GetCVar(CSCVars.IntifaceAddress);
        // _CS end: keep pending address in sync with archived cvar

        CharacterConsentFreetext.TextRope = new Rope.Leaf(consent.CharacterFreetext);
        ConsentFreetext.TextRope = new Rope.Leaf(consent.Freetext);

        if (ConsentList.ChildCount > 0)
            ConsentList.RemoveAllChildren();
        _entries.Clear();

        var consentprototypelist = _protoManager.EnumeratePrototypes<ConsentTogglePrototype>().ToList();
        consentprototypelist.Sort();

        foreach (var prototype in consentprototypelist)
        {
            if (prototype.Unused)
                continue;
            AddConsentEntry(prototype, consent);
        }

        if (_intifaceAddressEdit != null)
            _intifaceAddressEdit.Text = _pendingIntifaceAddress;

        SetIntifaceStatus(Loc.GetString("toy-control-intiface-status-unknown"));

        SaveConsentSettings.Disabled = true;
        SaveLabel.Text = "";
        UpdatePreview();
    }

    // _CS start: Intiface connection test helpers
    private void SetIntifaceStatus(string text)
    {
        if (_intifaceStatusLabel != null)
            _intifaceStatusLabel.Text = text;
    }

    private void OnTestIntifaceButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (_intifaceAddressEdit == null)
            return;

        _ = TestIntifaceConnectionAsync(_intifaceAddressEdit.Text);
    }

    private async Task TestIntifaceConnectionAsync(string address)
    {
        var version = ++_intifaceTestVersion;
        if (_intifaceTestButton != null)
            _intifaceTestButton.Disabled = true;

        SetIntifaceStatus(Loc.GetString("toy-control-intiface-status-testing"));

        using var adapter = new IntifaceWebsocketAdapter();
        adapter.SetServerAddress(address);
        var ok = await adapter.TestConnectionAsync();

        if (version == _intifaceTestVersion)
        {
            var text = ok
                ? Loc.GetString("toy-control-intiface-status-connected")
                : Loc.GetString("toy-control-intiface-status-failed", ("reason", adapter.LastError));
            SetIntifaceStatus(text);
        }

        if (_intifaceTestButton != null)
            _intifaceTestButton.Disabled = false;
    }
    // _CS end: Intiface connection test helpers

    private struct EntryState
    {
        public ConsentTogglePrototype Consent;
        public Button? Button;
    }
}
