- type: job
  id: Cadet
  name: job-name-cadet-nf
  description: job-description-cadet-nf
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # frontier = 6 hrs | CS = 12 hrs, TIME IN SECONDS
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3600 # frontier = 18 hrs | CS = 1 hrs, joblist requirement.
#      inverted: true # Leave slots open for newer, less confident players. | We use a different joblisting system. This can't be inverted. Plus, it's kinda kills rookie roleplay.
  startingGear: CadetGear
  icon: JobIconCadetNF
  supervisors: job-supervisors-cadet
  weight: 70
  displayWeight: 10
  canBeAntag: false
  accessGroups:
  - CadetNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: CadetGear
  equipment:
    pocket1: NFWeaponPistolUniversalNfsdLessLethal
    pocket2: BookSecurity
  storage:
    back:
    - Flash
    - NFMagazineHighCapacityPistol35
    - NFMagazineHighCapacityPistol35Rubber
    - FrontierUplinkCoin10
